# Generated by Django 4.0.3 on 2022-03-15 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bio',
            old_name='fist_choice',
            new_name='first_choice',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='year',
        ),
        migrations.AddField(
            model_name='bio',
            name='year_of_completion',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
