# Generated by Django 4.0.3 on 2022-03-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0005_alter_applicant_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='is_applicant',
            field=models.BooleanField(default=True),
        ),
    ]
