# Generated by Django 4.0.3 on 2022-03-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0006_applicant_is_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='date_admitted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
