# Generated by Django 4.0.3 on 2022-03-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0007_applicant_date_admitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='number_of_visits',
            field=models.IntegerField(default=0),
        ),
    ]
