# Generated by Django 4.0.3 on 2022-03-16 22:38

import applicant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0008_applicant_number_of_visits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('program_id', models.CharField(default=applicant.models.Program.generate_id, max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bio',
            name='age',
        ),
        migrations.AddField(
            model_name='bio',
            name='d_o_b',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='father_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='guardian',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='mother_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='town',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default=applicant.models.Transaction.generate_id, max_length=25, unique=True),
        ),
    ]
