# Generated by Django 4.0.3 on 2022-03-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0009_program_remove_bio_age_bio_d_o_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
