# Generated by Django 4.0.3 on 2022-03-18 12:46

import applicant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0010_alter_bio_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='program_id',
        ),
        migrations.AddField(
            model_name='program',
            name='program_code',
            field=models.CharField(default=applicant.models.Program.generate_id, max_length=10),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
