# Generated by Django 4.0.3 on 2022-03-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0012_alter_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='has_paid',
            field=models.BooleanField(default=False),
        ),
    ]
