# Generated by Django 4.0.3 on 2022-03-17 22:48

import administration.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(default=administration.models.Admission.generate_id, max_length=15)),
                ('revoked', models.BooleanField(default=False)),
                ('date_revoked', models.DateField(auto_now=True, null=True)),
                ('date_admitted', models.DateField(auto_now_add=True)),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_administrator', to=settings.AUTH_USER_MODEL)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_applicant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
