# Generated by Django 4.0.3 on 2022-03-18 00:03

import administration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_code', models.CharField(default=administration.models.Program.generate_id, max_length=10)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
